/**
 * @file This file was generated by ax-lib generator.
 * @copyright AvidXchange Inc.
 */
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { UsrRolesFeatureRoutingModule } from './routing/usr-roles-feature-routing.module';
import { UsrRolesFeatureContainerComponent } from './containers/usr-roles-feature-container/usr-roles-feature-container.component';
import { UsrRolesListContainerComponent } from './containers/usr-roles-list-container/usr-roles-list-container.component';

@NgModule({
  imports: [CommonModule, UsrRolesFeatureRoutingModule],
  declarations: [UsrRolesFeatureContainerComponent, UsrRolesListContainerComponent],
})
export class UsrRolesFeatureModule {}
