/**
 * @file This file was generated by ax-app generator.
 * @copyright AvidXchange Inc.
 */

import { ErrorHandler, NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { RemoteEntryComponent } from './entry.component';
import { HttpClientModule, HTTP_INTERCEPTORS } from '@angular/common/http';
import { TranslateModule } from '@ngx-translate/core';
import {
  AuthTokenInterceptor,
  EntitlementsService,
  TenantService,
} from '@ui-coe/tenant/data-access';
import { remoteRoutes } from './entry.routes';
import { AppGuard } from '@ui-coe/shared/util/guards';
import { ConfigService, ErrorHandlerService, LoggingService } from '@ui-coe/shared/util/services';

@NgModule({
  declarations: [RemoteEntryComponent],
  imports: [
    CommonModule,
    RouterModule.forChild(remoteRoutes),
    HttpClientModule,
    TranslateModule.forRoot(),
  ],
  providers: [
    // this is needed for remote entry module so intercaptors can intercept feature http call and add necessary headers for bff
    TenantService,
    LoggingService,
    ConfigService,
    {
      provide: ErrorHandler,
      useClass: ErrorHandlerService,
    },
    AppGuard,
    EntitlementsService,
  ],
  exports: [],
})
export class RemoteEntryModule {}
