/**
 * @file This file was generated by ax-lib generator.
 * @copyright AvidXchange Inc.
 */
import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';
import { UsrMgmtFeatureContainerComponent } from '../containers/usr-mgmt-feature-container/usr-mgmt-feature-container.component';
import { UsrMgmtListContainerComponent } from '../containers/usr-mgmt-list-container/usr-mgmt-list-container.component';
import { USR_MGMT_LIST } from './usr-mgmt-routes';

const routes: Routes = [
  {
    path: '',
    component: UsrMgmtFeatureContainerComponent,
    children: [
      {
        path: '',
        pathMatch: 'full',
        redirectTo: USR_MGMT_LIST,
      },
      {
        path: USR_MGMT_LIST,
        component: UsrMgmtListContainerComponent,
      },
    ],
  },
];

@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule],
})
export class UsrMgmtFeatureRoutingModule {}
