export enum ContentKeys {
  TITLE = 'managePageTitle',
  DEFAULT_PAGE_CONTENT = 'defaultDetailsPage',
  ENTITY_DETAILS_TOASTER = 'entityDetails.toaster',
  ITEM_ACTIVATE_DEACTIVATE_TOASTER = 'detailsPage.toaster',
  DETAILS_REQUIRED_ERROR = 'detailsPage.requiredErrorMessage',
  DETAILS_MAX_LENGTH_ERROR = 'detailsPage.maxLengthErrorMessage',
  ADDRESS_ACTIVATE_SUCCESS_TOASTER = 'detailsPage.addressSection.activateAddressSuccessToastMessageText',
  ADDRESS_DEACTIVATE_SUCCESS_TOASTER = 'detailsPage.addressSection.deactivateAddressSuccessToastMessageText',
  ADDRESS_ACTIVATE_FAILURE_TOASTER = 'detailsPage.addressSection.activateAddressFailureToastMessageText',
  ADDRESS_DEACTIVATE_FAILURE_TOASTER = 'detailsPage.addressSection.deactivateAddressFailureToastMessageText',
  DETAILS_PAGE_ADDRESSES_CONTENT = 'detailsPage.addressSection',
  DETAILS_CONTENT = 'detailsPage',
  DETAILS_LIST_SUBTITLE = 'detailsPage.subtitle',
  BUS_LEVEL_RENAME_REQUIRED_ERROR = 'businessLevelRename.requiredErrorMessage',
  BUS_LEVEL_RENAME_SUCCESS_TOASTER = 'businessLevelRename.toaster.success',
  BUS_LEVEL_RENAME_FAILURE_TOASTER = 'businessLevelRename.toaster.error',
  ADDRESS_EDIT_SUCCESS_TOASTER = 'detailsPage.addressSection.editAddressSuccessToastMessageText',
  ADDRESS_EDIT_FAILURE_TOASTER = 'detailsPage.addressSection.editAddressFailureToastMessageText',
}
