parameters:
  azureServiceConnection: ''
  domain: ''
  capability: 'default'
  tfDirectory: ''
  stages: {}

stages:
  - ${{ each stage in parameters.stages }}:
      - stage: ${{ stage.name }}
        displayName: 'Deploy ${{ stage.name }} Front Door Infrastructure using Terraform'
        dependsOn: ${{ stage.dependsOn }}
        variables:
          - template: '../frontdoor/variables/${{ lower(stage.environment) }}.yml'
        jobs:
          - job:
            displayName: Update Security Policy
            container: cicd_devtools
            steps:
              - checkout: self

              - task: NodeTool@0
                inputs:
                  versionSpec: '16.x'
                displayName: 'Install Node.js'

              - task: AzureCLI@2
                inputs:
                  azureSubscription: ${{ stage.serviceConnection }}
                  scriptType: 'bash'
                  scriptLocation: 'inlineScript'
                  inlineScript: |
                    node $(System.DefaultWorkingDirectory)/tools/scripts/fd-security.js --resourceGroup=$(resourceGroup) --fdName=$(fdProfileName) --securityPolicyName=$(securityPolicy)
