/**
 * @file This file was generated by ax-lib generator.
 * @copyright AvidXchange Inc.
 */
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatTableModule } from '@angular/material/table';
import { ScrollingModule } from '@angular/cdk/scrolling';
import { TranslateLoader, TranslateModule } from '@ngx-translate/core';

import { TenantUiModule } from '@ui-coe/tenant/ui';
import { TenantDataAccessModule } from '@ui-coe/tenant/data-access';
import { SharedUtilDirectivesModule } from '@ui-coe/shared/util/directives';
import { TenantFeatureRoutingModule } from './routing/tenant-feature-routing.module';
import {
  TenantAddContainerComponent,
  TenantFeatureContainerComponent,
  TenantListContainerComponent,
  TenantManageContainerComponent,
} from './containers';
import { SharedUiV2Module, TableComponent } from '@ui-coe/shared/ui-v2';
import { ContentFacade, CustomTranslateLoader } from '@ui-coe/shared/data-access/content';
import { HttpClient } from '@angular/common/http';
import { ConfigService, FeatureFlagService } from '@ui-coe/shared/util/services';
import { AxTranslatePipe } from '@ui-coe/shared/util/pipes';

@NgModule({
  imports: [
    TableComponent,
    CommonModule,
    MatTableModule,
    ScrollingModule,
    TenantDataAccessModule,
    TenantFeatureRoutingModule,
    TenantUiModule,
    TranslateModule.forChild({
      loader: {
        provide: TranslateLoader,
        useClass: CustomTranslateLoader,
        deps: [HttpClient, FeatureFlagService, ConfigService, ContentFacade],
      },
      defaultLanguage: 'en',
    }),
    AxTranslatePipe,
    SharedUtilDirectivesModule,
    SharedUiV2Module,
  ],
  declarations: [
    TenantFeatureContainerComponent,
    TenantListContainerComponent,
    TenantAddContainerComponent,
    TenantManageContainerComponent,
  ],
})
export class TenantFeatureModule {}
