/**
 * @file This file was generated by ax-lib generator.
 * @copyright AvidXchange Inc.
 */
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { TranslateModule } from '@ngx-translate/core';

import {
  BusHierTreeComponent,
  BusHierTreeNodeComponent,
  BusHierUiModule,
} from '@ui-coe/bus-hier/ui';
import { BusHierFeatureRoutingModule } from './routing/bus-hier-feature-routing.module';
import { BusHierFeatureContainerComponent } from './containers/bus-hier-feature-container/bus-hier-feature-container.component';
import { BusHierManageContainerComponent } from './containers/bus-hier-manage-container/bus-hier-manage-container.component';
import { BusHierDataAccessModule } from '@ui-coe/bus-hier/data-access';
import { SharedUiV2Module } from '@ui-coe/shared/ui-v2';
import { AxTranslatePipe } from '@ui-coe/shared/util/pipes';

@NgModule({
  imports: [
    CommonModule,
    BusHierFeatureRoutingModule,
    BusHierUiModule,
    TranslateModule,
    BusHierTreeComponent,
    BusHierTreeNodeComponent,
    BusHierDataAccessModule,
    SharedUiV2Module,
    AxTranslatePipe,
  ],
  declarations: [BusHierFeatureContainerComponent, BusHierManageContainerComponent],
})
export class BusHierFeatureModule {}
