/**
 * @file This file was generated by ax-app generator.
 * @copyright AvidXchange Inc.
 */
import { Component } from '@angular/core';

@Component({
  selector: 'ax-remote-spa-entry',
  template: `usr-roles-spa Entry Component <router-outlet></router-outlet>`,
})
export class RemoteEntryComponent {}
