/**
 * @file This file was generated by ax-app generator.
 * @copyright AvidXchange Inc.
 */
import { Injectable } from '@angular/core';
import { UrlTree } from '@angular/router';
import { ConfigService } from '@ui-coe/shared/util/services';

@Injectable()
export class AppGuard {
  constructor(private configService: ConfigService) {}

  async canActivate(): Promise<boolean | UrlTree> {
    await this.configService.loadAppConfig(
      this.configService.getMfeManifest('team-maturity-spa') + '/assets/config/app.config.json'
    );

    return this.configService.appConfig ? true : false;
  }
}
