/**
 * @file This file was generated by ax-lib generator.
 * @copyright AvidXchange Inc.
 */
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  AvatarComponent,
  ButtonComponent,
  InputComponent,
  SharedUiV2Module,
  SideSheetV2Component,
  TableComponent,
  TagComponent,
  TooltipDirective,
} from '@ui-coe/shared/ui-v2';
import {
  UsrMgmtHeaderComponent,
  UsrMgmtLayoutComponent,
  UsrMgmtListComponent,
  UsrMgmtPageTitleComponent,
  UsrCreateEditComponent,
  MenuComponent,
} from './components';
@NgModule({
  imports: [
    CommonModule,
    SharedUiV2Module,
    ButtonComponent,
    TableComponent,
    TagComponent,
    AvatarComponent,
    InputComponent,
    SideSheetV2Component,
    TooltipDirective,
    MenuComponent,
  ],
  declarations: [
    UsrMgmtLayoutComponent,
    UsrMgmtHeaderComponent,
    UsrMgmtPageTitleComponent,
    UsrMgmtListComponent,
    UsrCreateEditComponent,
  ],
  exports: [
    SharedUiV2Module,
    UsrMgmtLayoutComponent,
    UsrMgmtHeaderComponent,
    UsrMgmtPageTitleComponent,
    UsrMgmtListComponent,
    UsrCreateEditComponent,
    MenuComponent,
  ],
})
export class UsrMgmtUiModule {}
