/**
 * @file This file was generated by ax-app generator.
 * @copyright AvidXchange Inc.
 */

import { NgModule } from '@angular/core';
import { RouterModule } from '@angular/router';
import { LoginCallbackComponent, LogoutComponent } from '@ui-coe/shell/navigation/feature';

@NgModule({
  declarations: [],
  imports: [
    RouterModule.forRoot(
      [
        { path: 'login/callback', component: LoginCallbackComponent },
        {
          path: '',
          pathMatch: 'full',
          redirectTo: 'dashboard',
        },
        {
          path: 'logout',
          component: LogoutComponent,
        },
      ],
      {
        initialNavigation: window['Cypress']
          ? undefined
          : window !== window.parent && !window.opener
          ? 'disabled'
          : undefined,
      }
    ),
  ],
  exports: [RouterModule],
})
export class AppRoutingModule {}
