/**
 * @file This file was generated by ax-app generator.
 * @copyright AvidXchange Inc.
 */
import { HttpModule, HttpService } from '@nestjs/axios';
import { DynamicModule, Module } from '@nestjs/common';
import { MockHttpService, defaultSortFilterConfig } from '@ui-coe/shared/bff/data-access';
import { MOCK_FILE_PATH } from '../shared';

@Module({})
export class UsrMgmtBffHttpModule {
  static register(mockEnv: boolean): DynamicModule {
    return {
      module: UsrMgmtBffHttpModule,
      providers: mockEnv
        ? [
            {
              provide: HttpService,
              useClass: MockHttpService,
            },
            {
              provide: MOCK_FILE_PATH,
              useValue: 'assets/mock/json',
            },
            {
              provide: 'SORT_FILTER_CONFIG',
              useValue: defaultSortFilterConfig,
            },
          ]
        : [],
      imports: mockEnv ? [] : [HttpModule],
      exports: mockEnv ? [HttpService] : [HttpModule],
    };
  }
}
