/**
 * @file This file was generated by ax-lib generator.
 * @copyright AvidXchange Inc.
 */
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { StoreModule } from '@ngrx/store';
import { EffectsModule } from '@ngrx/effects';
import { UserFacade } from './+state';
import * as fromUser from './+state/user/user.reducer';
import { UserEffects } from './+state/user/user.effects';

@NgModule({
  imports: [
    CommonModule,
    // add your reducer below
    StoreModule.forFeature(fromUser.userFeatureKey, fromUser.reducer),
    // add your effects below
    EffectsModule.forFeature(UserEffects),
  ],
  providers: [UserFacade],
})
export class UsrMgmtDataAccessModule {}
