/* 🤖 this file was generated by svg-to-ts*/
export const axIconAscending: AxIcon = {
  name: 'ascending',
  data: `<svg width="20" height="20" xmlns="http://www.w3.org/2000/svg"><path d="M5 12l5-5 5 5z" fill="#333" fill-rule="nonzero"/></svg>`,
};
export const axIconClock: AxIcon = {
  name: 'clock',
  data: `<svg xmlns="http://www.w3.org/2000/svg" width="62" height="62"><g fill="none" fill-rule="evenodd" transform="translate(.333 .333)"><circle cx="30.667" cy="30.667" r="30.667" fill="#404041"/><circle cx="30.667" cy="30.667" r="26.286" fill="#FBFDFF"/><g fill="#404041" transform="translate(29.79 3.505)"><rect width="2.044" height="8.324" y="48.19" rx="1"/><rect width="2.044" height="5.257" rx="1"/></g><g fill="#404041" transform="rotate(90 14.165 44.248)"><rect width="2.044" height="8.324" y="49.213" rx="1"/><rect width="2.044" height="7.302" rx="1"/></g><g transform="translate(15.625 11.39)"><path fill="#C32526" d="M17.168 15.836c.19.15.224.424.075.615L2.14 35.784a.439.439 0 01-.69-.54l15.104-19.332a.438.438 0 01.615-.076z"/><rect width="2.629" height="16.648" x="13.727" fill="#404041" rx="1.314"/><rect width="12.267" height="2.629" x="17.67" y="18.4" fill="#404041" rx="1.314"/><circle cx="15.333" cy="19.422" r="4.089" fill="#FFC63E"/></g></g></svg>`,
};
export const axIconClose: AxIcon = {
  name: 'close',
  data: `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="16" height="16" viewBox="0 0 16 16"><defs><filter id="1rp3hp7oea"><feColorMatrix in="SourceGraphic" values="0 0 0 0 1.000000 0 0 0 0 1.000000 0 0 0 0 1.000000 0 0 0 1.000000 0"/></filter><path id="ih6cqiqsxb" d="M8.73 7.216l5.504-5.504c.175-.198.267-.456.256-.72-.038-.359-.266-.67-.596-.815-.33-.145-.713-.103-1.003.111l-5.584 5.52L1.803.288C1.406-.096.776-.096.38.288.2.48.098.73.091.992c.003.268.106.524.288.72L5.9 7.216.379 12.8c-.17.171-.273.399-.288.64.026.532.46.952.992.96.27-.002.53-.111.72-.304L7.307 8.64l5.584 5.504c.176.158.403.249.64.256.513-.038.921-.446.96-.96-.008-.237-.099-.463-.257-.64L8.731 7.216z"/></defs><g fill="none" fill-rule="evenodd"><g filter="url(#1rp3hp7oea)" transform="translate(-1141 -265)"><g><g><g transform="translate(1141 265) translate(0 .8) translate(.709)"><mask id="v3s32uifwc" fill="#fff"><use xlink:href="#ih6cqiqsxb"/></mask><use fill="#333" fill-rule="nonzero" xlink:href="#ih6cqiqsxb"/><g mask="url(#v3s32uifwc)"><g><path fill="#333" d="M0 0H80V80H0z" transform="translate(-30.4 -32)"/></g></g></g></g></g></g></g></svg>`,
};
export const axIconDescending: AxIcon = {
  name: 'descending',
  data: `<svg width="20" height="20" xmlns="http://www.w3.org/2000/svg"><path d="M5 8l5 5 5-5z" fill="#333" fill-rule="nonzero"/></svg>`,
};
export const axIconIconWarningRed: AxIcon = {
  name: 'icon_warning_red',
  data: `<svg xmlns="http://www.w3.org/2000/svg" width="32" height="28"><path fill="#c32727" fill-rule="evenodd" d="M16.93.236c.278.161.51.393.67.67l14.123 24.312A1.851 1.851 0 0130.122 28H1.878a1.852 1.852 0 01-1.602-2.782L14.4.907a1.85 1.85 0 012.53-.671zm.838 19.236h-3.485v3.388h3.485v-3.388zm0-9.595h-3.485v8.404h3.485V9.877z"/></svg>`,
};
export const axIconLogout: AxIcon = {
  name: 'logout',
  data: `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="19" height="20"><defs><path id="a" d="M10.11.176v1.411H1.644V18.52h8.466v1.41H.233V.176h9.877zm1.41 2.822l7.055 7.055-7.054 7.055-1.411-1.411 4.233-4.233H4.466V8.642h9.877L10.11 4.409 11.52 3z"/></defs><g fill="none" fill-rule="evenodd"><mask id="b" fill="#fff"><use xlink:href="#a"/></mask><use fill="#FBFDFF" fill-rule="nonzero" xlink:href="#a"/><g mask="url(#b)"><path fill="#FBFDFF" d="M-40-40H60V60H-40z"/></g></g></svg>`,
};
export const axIconPaper: AxIcon = {
  name: 'paper',
  data: `<svg width="50" height="50" viewBox="0 0 50 50" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M4 6C4 4.34315 5.34315 3 7 3H23.6552L31 3C32.6569 3 34 4.34315 34 6V13.2703V38C34 39.6569 32.6569 41 31 41H7C5.34315 41 4 39.6569 4 38V6Z" fill="#1980A9"/><path d="M15 11C15 9.34315 16.3431 8 18 8L34 8L45 19L45 43C45 44.6569 43.6569 46 42 46H18C16.3431 46 15 44.6569 15 43V11Z" fill="#A6DAF2"/><path d="M34 16V8L45 19H37C35.3431 19 34 17.6569 34 16Z" fill="#1980A9"/><rect x="19" y="37" width="22" height="4" rx="2" fill="#1980A9"/><path d="M19 31C19 29.8954 19.8954 29 21 29H31C32.1046 29 33 29.8954 33 31C33 32.1046 32.1046 33 31 33H21C19.8954 33 19 32.1046 19 31Z" fill="#1980A9"/></svg>`,
};
export const axIconSearch: AxIcon = {
  name: 'search',
  data: `<svg xmlns="http://www.w3.org/2000/svg" width="15" height="15"><path fill="#FFF" d="M10.286 6.286c0-2.206-1.795-4-4-4-2.206 0-4 1.794-4 4 0 2.205 1.794 4 4 4 2.205 0 4-1.795 4-4zm4.571 7.428c0 .625-.518 1.143-1.143 1.143-.303 0-.598-.125-.803-.34l-3.063-3.053a6.262 6.262 0 01-3.562 1.107A6.283 6.283 0 010 6.286 6.284 6.284 0 016.286 0a6.283 6.283 0 016.285 6.286 6.262 6.262 0 01-1.107 3.562l3.063 3.063c.205.205.33.5.33.803z"/></svg>`,
};
export const axIconUnsorted: AxIcon = {
  name: 'unsorted',
  data: `<svg width="20" height="20" xmlns="http://www.w3.org/2000/svg"><g fill="#333" fill-rule="nonzero" fill-opacity=".5"><path d="M5 8l5-5 5 5zM5 11l5 5 5-5z"/></g></svg>`,
};
export const axIconUser: AxIcon = {
  name: 'user',
  data: `<svg xmlns="http://www.w3.org/2000/svg" width="31" height="32"><g fill="#FFF" transform="translate(1)"><circle cx="14.613" cy="8" r="8"/><path d="M14.613 17.36C6.933 17.36.64 22.08 0 28.347c-.06.598.144 1.192.56 1.626.405.459.988.72 1.6.72h24.933c.612 0 1.195-.261 1.6-.72.41-.437.605-1.032.534-1.626-.614-6.267-6.907-10.987-14.614-10.987z"/></g></svg>`,
};
export const axIconUsers: AxIcon = {
  name: 'users',
  data: `<svg width="50" height="50" viewBox="0 0 50 50" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M33 26.7143C33 23.1994 25.2843 19 17 19C8.71573 19 2 23.1994 2 26.7143L2 35.5C2 36.3284 2.67157 37 3.5 37H31.5C32.3284 37 33 36.3284 33 35.5V26.7143Z" fill="#435088"/><circle cx="17" cy="11" r="8" fill="#435088"/><path d="M48 36.7143C48 33.1994 41.2843 29 33 29C24.7157 29 18 33.1994 18 36.7143L18 45.5C18 46.3284 18.6716 47 19.5 47H46.5C47.3284 47 48 46.3284 48 45.5V36.7143Z" fill="#99B6FF"/><circle cx="33" cy="21" r="8" fill="#99B6FF"/></svg>`,
};
export const axIconWarning: AxIcon = {
  name: 'warning',
  data: `<svg width="50" height="50" viewBox="0 0 50 50" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M22.3591 6.68835C23.4921 4.58609 26.5078 4.58611 27.6408 6.68839L46.4314 41.5541C47.5086 43.5528 46.061 45.9774 43.7905 45.9774H6.20876C3.93822 45.9774 2.49066 43.5528 3.56789 41.5541L22.3591 6.68835Z" fill="#CF45B2"/><path d="M25 18.0298C26.1046 18.0298 27 18.9252 27 20.0298L27 30.4991C27 31.6037 26.1046 32.4991 25 32.4991C23.8954 32.4991 23 31.6037 23 30.4991L23 20.0298C23 18.9252 23.8954 18.0298 25 18.0298Z" fill="#752162"/><path d="M22.5 37.5131C22.5 36.1323 23.6193 35.0131 25 35.0131C26.3807 35.0131 27.5 36.1323 27.5 37.5131C27.5 38.8938 26.3807 40.0131 25 40.0131C23.6193 40.0131 22.5 38.8938 22.5 37.5131Z" fill="#752162"/></svg>`,
};
export const axChevron: AxIcon = {
  name: 'chevron',
  data: `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" focusable="false" width="1em" height="1em" style="-ms-transform: rotate(360deg); -webkit-transform: rotate(360deg); transform: rotate(360deg);" preserveAspectRatio="xMidYMid meet" viewBox="0 0 32 32"><g fill="none" stroke="#fff" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"><path d="M30 12L16 24L2 12"/></g></svg>`,
};
export interface AxIcon {
  name: string;
  data: string;
}
