/**
 * @file This file was generated by ax-app generator.
 * @copyright AvidXchange Inc.
 */

import { DynamicModule, Module } from '@nestjs/common';
import { HttpService, HttpModule } from '@nestjs/axios';
import { ISortFilterConfig, MockHttpService } from '@ui-coe/shared/bff/data-access';
import { MOCK_FILE_PATH } from '../shared';

const sortFilterConfig: ISortFilterConfig = {
  sortKey: 'sort_by',
  sortDirectionKey: {
    ascending: 'asc:',
    descending: 'desc:',
  },
  limitKey: 'limit',
  offsetKey: 'offset',
  filterKeys: [
    'site_name',
    'customer_name',
    'tenant_status',
    'tenant_type',
    'owner_type',
    'storage_region',
    'created_date',
  ],
};

@Module({})
export class TenantApiHttpModule {
  static register(mockEnv: boolean): DynamicModule {
    return {
      module: TenantApiHttpModule,
      providers: mockEnv
        ? [
            {
              provide: HttpService,
              useClass: MockHttpService,
            },
            {
              provide: MOCK_FILE_PATH,
              useValue: 'assets/mock/json',
            },
            {
              provide: 'SORT_FILTER_CONFIG',
              useValue: sortFilterConfig,
            },
          ]
        : [],
      imports: mockEnv ? [] : [HttpModule],
      exports: mockEnv ? [HttpService] : [HttpModule],
    };
  }
}
