/**
 * @file This file was generated by ax-lib generator.
 * @copyright AvidXchange Inc.
 */
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { ShellNavigationFeatureRoutingModule } from './routing/shell-navigation-feature-routing.module';
import { ShellNavigationFeatureContainerComponent } from './containers/shell-navigation-feature-container/shell-navigation-feature-container.component';
import { MaterialModule } from './material.module';
import { ShellNavigationDataAccessModule } from '@ui-coe/shell/navigation/data-access';
import { DashboardComponent } from './containers/dashboard/dashboard.component';
import { LogoutComponent } from './containers/logout/logout.component';
import { ButtonComponent, HeaderComponent, SidenavComponent } from '@ui-coe/shared/ui-v2';

@NgModule({
  imports: [
    CommonModule,
    ShellNavigationFeatureRoutingModule,
    MaterialModule,
    ShellNavigationDataAccessModule,
    ButtonComponent,
    HeaderComponent,
    SidenavComponent,
  ],
  declarations: [ShellNavigationFeatureContainerComponent, DashboardComponent, LogoutComponent],
})
export class ShellNavigationFeatureModule {}
