######################################################
# @file This file was generated by ax-app generator.
# @copyright AvidXchange Inc.
######################################################
Feature: UsrMgmt
    @e2e-test
    # add your scenarios below
    Scenario: Displaying of UI Elements
        Given that I am on the User Management List page
        Then the User Management title must be displayed
        Then the Import and Add buttons must be displayed
        Then the table must be displayed