/**
 * @file This file was generated by ax-app generator.
 * @copyright AvidXchange Inc.
 */

import { ErrorHandler, NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { ConfigService, ErrorHandlerService, LoggingService } from '@ui-coe/shared/util/services';
import { RemoteEntryComponent } from './entry.component';
import { HttpClient, HttpClientModule, HTTP_INTERCEPTORS } from '@angular/common/http';
import { TranslateLoader, TranslateModule } from '@ngx-translate/core';
import { TranslateHttpLoader } from '@ngx-translate/http-loader';
import { AppGuard } from '@ui-coe/shared/util/guards';
import { remoteRoutes } from './entry.routes';
import {
  AuthTokenInterceptor,
  BusHierService,
  ErpService,
  OrganizationService,
  EntityService,
} from '@ui-coe/bus-hier/data-access';
import { BusinessLevelService } from 'libs/bus-hier/data-access/src/lib/services/business-level.service';

export function createTranslateLoaderRemote(http: HttpClient, config: ConfigService) {
  return new TranslateHttpLoader(http, `${config.get('baseUrl')}/assets/i18n/`, '.json');
}

@NgModule({
  declarations: [RemoteEntryComponent],
  imports: [
    CommonModule,
    RouterModule.forChild(remoteRoutes),
    HttpClientModule,
    TranslateModule.forRoot({
      loader: {
        provide: TranslateLoader,
        useFactory: createTranslateLoaderRemote,
        deps: [HttpClient, ConfigService],
      },
      defaultLanguage: 'en',
    }),
  ],
  providers: [
    // this is needed for remote entry module so intercaptors can intercept feature http call and add necessary headers for bff
    BusHierService,
    BusinessLevelService,
    ErpService,
    OrganizationService,
    EntityService,
    AppGuard,
    LoggingService,
    ConfigService,
    {
      provide: ErrorHandler,
      useClass: ErrorHandlerService,
    },
    {
      provide: HTTP_INTERCEPTORS,
      useClass: AuthTokenInterceptor,
      multi: true,
    },
  ],
  exports: [],
})
export class RemoteEntryModule {}
