/**
 * @file This file was generated by ax-lib generator.
 * @copyright AvidXchange Inc.
 */
import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';
import { TenantFeatureContainerComponent, TenantListContainerComponent } from '../containers';
import { TenantAddContainerComponent } from '../containers/tenant-add-container/tenant-add-container.component';
import { TenantManageContainerComponent } from '../containers/tenant-manage-container/tenant-manage-container.component';
import { ADD_TENANT, LIST_TENANTS, MANAGE_TENANT } from './tenant-feature-routes';

const routes: Routes = [
  {
    path: '',
    component: TenantFeatureContainerComponent,
    children: [
      {
        path: '',
        pathMatch: 'full',
        redirectTo: LIST_TENANTS,
      },
      {
        path: LIST_TENANTS,
        component: TenantListContainerComponent,
      },
      {
        path: ADD_TENANT,
        component: TenantAddContainerComponent,
      },
      {
        path: MANAGE_TENANT,
        component: TenantManageContainerComponent,
      },
    ],
  },
];

@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule],
})
export class TenantFeatureRoutingModule {}
