/**
 * @file This file was generated by ax-app generator.
 * @copyright AvidXchange Inc.
 */
import { Test, TestingModule } from '@nestjs/testing';
import { MOCK_ENV } from '../app/shared';
import { HttpConfigService } from './http-config.service';
import { ConfigService } from '@nestjs/config';
import { httpConfig } from '../app/models';

describe('HttpConfigService', () => {
  let service: HttpConfigService;
  const config: httpConfig = {
    path: 'foo/bar/baz',
    localPath: '/get-user-account-by-id.json',
  };

  beforeEach(async () => {
    const module: TestingModule = await Test.createTestingModule({
      providers: [
        ConfigService,
        HttpConfigService,
        {
          provide: MOCK_ENV,
          useValue: false,
        },
      ],
    }).compile();

    service = module.get<HttpConfigService>(HttpConfigService);
  });

  describe('getPath non-mock', () => {
    it('should be defined', () => {
      expect(service).toBeDefined();
    });

    it('should return the correct path for mock', () => {
      // TODO: revert this when we switch to new orchestration platform
      expect(service['getPath'](config)).toBe(config.localPath);
    });
  });
});
