/**
 * @file This file was generated by ax-app generator.
 * @copyright AvidXchange Inc.
 */
export * from './app.po';
export * from './e2e';

// TODO: see if there is a way to avoid doing this
Cypress.on('uncaught:exception', err => {
  if (err.message.includes(`Cannot use 'import.meta' outside a module`)) {
    return false;
  }
  return true;
});
