export enum ContentKeys {
  TITLE = 'title',
  ADD_BTN = 'addButton',
  DETAILS_TITLE = 'detailsTitle',
  MANAGE_DETAILS_TITLE = 'manageDetailsTitle',
  TABLE_DISPLAYED_COLUMNS = 'tenantList.columnHeaders',
  SITE_NAME_HEADER = 'tenantList.columnHeaders.siteName',
  DATE_CREATED_HEADER = 'tenantList.columnHeaders.dateCreated',
  STATUS_HEADER = 'tenantList.columnHeaders.status',
  NEW_BADGE_TEXT = 'tenantList.newBadge',
  SIDE_MENU_CUSTOMER_DETAILS = 'customerDetails.sideMenu.customerDetails',
  SIDE_MENU_ENTITLEMENTS = 'customerDetails.sideMenu.entitlements',
  SITE_NAME_LABEL_TEXT = 'customerDetails.customerDetailsCard.siteNameLabelText',
  CMP_LABEL_TEXT = 'customerDetails.customerDetailsCard.cmpLabelText',
  SITE_ID_LABEL_TEXT = 'customerDetails.customerDetailsCard.siteIdLabelText',
  CUSTOMER_NAME_LABEL_TEXT = 'customerDetails.customerDetailsCard.customerNameLabelText',
  ACCOUNT_ID_LABEL_TEXT = 'customerDetails.customerDetailsCard.accountIdLabelText',
  CUSTOMER_DETAILS_CARD_TITLE = 'customerDetails.customerDetailsCard.title',
  CUSTOMER_DETAILS_CARD_SUBMIT_BUTTON_TEXT = 'customerDetails.customerDetailsCard.submitButtonText',
  CUSTOMER_DETAILS_CARD_CMP_ID_HELPER_TEXT = 'customerDetails.customerDetailsCard.cmpIdHelperText',
  CUSTOMER_DETAILS_TENANT_TOASTER = 'customerDetails.toaster',
  ENTITLEMENTS_CARD_TITLE = 'customerDetails.entitlementsCard.title',
  ENTITLEMENTS_CARD_HELPER_TEXT = 'customerDetails.entitlementsCard.entitlementsHelperText',
}
