/**
 * @file This file was generated by ax-lib generator.
 * @copyright AvidXchange Inc.
 */
import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';
import { BusHierFeatureContainerComponent } from '../containers/bus-hier-feature-container/bus-hier-feature-container.component';
import { BusHierManageContainerComponent } from '../containers/bus-hier-manage-container/bus-hier-manage-container.component';
import { MANAGE_BUS_HIER } from './bus-hier-routes';

const routes: Routes = [
  {
    path: '',
    component: BusHierFeatureContainerComponent,
    children: [
      {
        path: '',
        pathMatch: 'full',
        redirectTo: MANAGE_BUS_HIER,
      },
      {
        path: MANAGE_BUS_HIER,
        component: BusHierManageContainerComponent,
      },
    ],
  },
];

@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule],
})
export class BusHierFeatureRoutingModule {}
