/**
 * @file This file was generated by ax-app generator.
 * @copyright AvidXchange Inc.
 */

import { Module } from '@nestjs/common';
import { ConfigModule } from '@nestjs/config';
import { environment } from '../environments/environment';
import { HttpConfigService } from '../services/http-config.service';
import { AppController } from './app.controller';
import { AppService } from './app.service';
import { MOCK_ENV } from './shared';
import { UsrRolesBffHttpModule } from './usr-roles-bff-http/usr-roles-bff-http.module';
import { RolesController } from './controllers/roles/roles.controller';
import { RolesService } from './controllers/roles/roles.service';

@Module({
  imports: [ConfigModule.forRoot(), UsrRolesBffHttpModule.register(environment.mock)],
  controllers: [AppController, RolesController],
  providers: [
    AppService,
    HttpConfigService,
    {
      provide: MOCK_ENV,
      useValue: environment.mock,
    },
    RolesService,
  ],
})
export class AppModule {}
