parameters:
- blockSize: auto
  columnName: p_Password
  fileName: AvidCapture_IndexerUsers.csv
  firstDataRow: 1
  name: p_Password
  nextRow: sequential
  nextValue: iteration
  onEnd: loop
  type: csv
- blockSize: auto
  columnName: p_UserName
  fileName: AvidCapture_IndexerUsers.csv
  firstDataRow: 1
  name: p_UserName
  nextRow: sequential
  nextValue: iteration
  onEnd: loop
  type: csv
- blockSize: auto
  columnName: p_BuyerID
  fileName: BuerData.csv
  firstDataRow: 1
  name: p_BuyerID
  nextRow: sequential
  nextValue: iteration
  onEnd: loop
  type: csv
