export const getGamesInLobbyResponse = [
  {
    _id: '',
    gameName: '',
    gameStatus: '',
    players: [
      {
        nickname: '',
        id: '',
        isHost: false,
        score: 0,
        brainsRolled: 0,
        shotgunsRolled: 0,
        initialRoll: true,
      },
    ],
    gameData: {
      hostId: '',
      turnIndex: 0,
      playerTurn: '',
      turns: [],
      winner: {
        id: '',
        name: '',
      },
      dicePool: [
        {
          1: '',
          2: '',
          3: '',
          4: '',
          5: '',
          6: '',
          color: '',
        },
        {
          1: '',
          2: '',
          3: '',
          4: '',
          5: '',
          6: '',
          color: '',
        },
        {
          1: '',
          2: '',
          3: '',
          4: '',
          5: '',
          6: '',
          color: '',
        },
        {
          1: '',
          2: '',
          3: '',
          4: '',
          5: '',
          6: '',
          color: '',
        },
        {
          1: '',
          2: '',
          3: '',
          4: '',
          5: '',
          6: '',
          color: '',
        },
        {
          1: '',
          2: '',
          3: '',
          4: '',
          5: '',
          6: '',
          color: '',
        },
        {
          1: '',
          2: '',
          3: '',
          4: '',
          5: '',
          6: '',
          color: '',
        },
        {
          1: '',
          2: '',
          3: '',
          4: '',
          5: '',
          6: '',
          color: '',
        },
        {
          1: '',
          2: '',
          3: '',
          4: '',
          5: '',
          6: '',
          color: '',
        },
        {
          1: '',
          2: '',
          3: '',
          4: '',
          5: '',
          6: '',
          color: '',
        },
        {
          1: '',
          2: '',
          3: '',
          4: '',
          5: '',
          6: '',
          color: '',
        },
        {
          1: '',
          2: '',
          3: '',
          4: '',
          5: '',
          6: '',
          color: '',
        },
        {
          1: '',
          2: '',
          3: '',
          4: '',
          5: '',
          6: '',
          color: '',
        },
      ],
      response: '',
    },
    chat: [
      {
        playerId: '',
        nickname: '',
        message: '',
      },
    ],
  },
];
