export enum AppActions {
  LOAD_USERS = '[User] Load Users',
  LOAD_USERS_SUCCESS = '[User] Load Users Success',
  LOAD_USERS_FAILURE = '[User] Load Users Failure',
  ADD_USER = '[User] Add User',
  ADD_USER_SUCCESS = '[User] Add User Success',
  ADD_USER_FAILURE = '[User] Add User Failure',
  EDIT_USER = '[User] Edit User',
  EDIT_USER_SUCCESS = '[User] Edit User Success',
  EDIT_USER_FAILURE = '[User] Edit User Failure',
  DISPLAY_TOAST = '[User] Display Toast',
  DISMISS_TOAST = '[User] Dismiss Toast',
  DEACTIVATE_USER = '[User] Deactive Users',
  DEACTIVATE_USER_SUCCESS = '[User] Deactive Users Success',
  DEACTIVATE_USER_FAILURE = '[User] Deactive Users Failure',
}
