/**
 * @file This file was generated by ax-lib generator.
 * @copyright AvidXchange Inc.
 */
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { StoreModule } from '@ngrx/store';
import { EffectsModule } from '@ngrx/effects';
import * as fromTree from './+state/tree/tree.reducer';
import { TreeEffects } from './+state/tree/tree.effects';
import { TreeFacade } from './+state/tree';
import * as details from './+state/details/details.reducer';
import { BusinessLevelEffects, DetailsEffects } from './+state';
import { DetailsFacade } from './+state';
import { ShellNavigationDataAccessModule } from '@ui-coe/shell/navigation/data-access';
import * as fromHistory from './+state/history/history.reducer';
import * as fromBusinessLevel from './+state/business-level/business-level.reducer';

@NgModule({
  imports: [
    CommonModule,
    // add your reducer below
    StoreModule.forFeature(fromTree.treeFeatureKey, fromTree.reducer),
    StoreModule.forFeature(details.detailsFeatureKey, details.reducer),
    StoreModule.forFeature(fromHistory.historyFeatureKey, fromHistory.reducer),
    StoreModule.forFeature(fromBusinessLevel.businessLevelFeatureKey, fromBusinessLevel.reducer),
    // add your effects below
    EffectsModule.forFeature(TreeEffects),
    EffectsModule.forFeature(DetailsEffects),
    EffectsModule.forFeature(BusinessLevelEffects),
    ShellNavigationDataAccessModule,
  ],
  providers: [TreeFacade, DetailsFacade],
})
export class BusHierDataAccessModule {}
