/**
 * @file This file was generated by ax-lib generator.
 * @copyright AvidXchange Inc.
 */
import { ErrorHandler, NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { StoreModule } from '@ngrx/store';
import { EffectsModule } from '@ngrx/effects';

import { TenantSharedTypesModule } from '@ui-coe/tenant/shared/types';
import { TenantSharedUtilModule } from '@ui-coe/tenant/shared/util';
import { ShellNavigationDataAccessModule } from '@ui-coe/shell/navigation/data-access';

import * as fromTenant from './+state/tenant/tenant.reducer';
import { TenantEffects, TenantFacade } from './+state';
import { SiteNameValidator } from './validators';
import * as fromEntitlements from './+state/entitlements/entitlements.reducer';
import { EntitlementsEffects } from './+state/entitlements/entitlements.effects';

@NgModule({
  imports: [
    CommonModule,
    StoreModule.forFeature(fromTenant.tenantFeatureKey, fromTenant.reducer),
    StoreModule.forFeature(
      fromEntitlements.entitlementsFeatureKey,
      fromEntitlements.entitlementsReducer
    ),
    EffectsModule.forFeature([TenantEffects, EntitlementsEffects]),
    ShellNavigationDataAccessModule,
    TenantSharedTypesModule,
    TenantSharedUtilModule,
  ],
  // This is necessary even if services are declared in root when app is working with app-shell
  providers: [TenantFacade, SiteNameValidator],
})
export class TenantDataAccessModule {}
