/**
 * @file This file was generated by ax-lib generator.
 * @copyright AvidXchange Inc.
 */
import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';
import { UsrRolesListContainerComponent, UsrRolesFeatureContainerComponent } from '../containers';
import { USR_ROLES_LIST } from './usr-roles-routes';

const routes: Routes = [
  {
    path: '',
    component: UsrRolesFeatureContainerComponent,
    children: [
      {
        path: '',
        pathMatch: 'full',
        redirectTo: USR_ROLES_LIST,
      },
      {
        path: USR_ROLES_LIST,
        component: UsrRolesListContainerComponent,
      },
    ],
  },
];

@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule],
})
export class UsrRolesFeatureRoutingModule {}
