/**
 * @file This file was generated by ax-app generator.
 * @copyright AvidXchange Inc.
 */

import { Module } from '@nestjs/common';
import { ConfigModule } from '@nestjs/config';
import { environment } from '../environments/environment';
import { HttpConfigService } from '../services/http-config.service';
import { AppController } from './app.controller';
import { AppService } from './app.service';
import { MOCK_ENV } from './shared';
import { VdrMgmtBffHttpModule } from './vdr-mgmt-bff-http/vdr-mgmt-bff-http.module';

@Module({
  imports: [ConfigModule.forRoot(), VdrMgmtBffHttpModule.register(environment.mock)],
  controllers: [AppController],
  providers: [
    AppService,
    HttpConfigService,
    {
      provide: MOCK_ENV,
      useValue: environment.mock,
    },
  ],
})
export class AppModule {}
