######################################################
# @file This file was generated by ax-app generator.
# @copyright AvidXchange Inc.
######################################################
Feature: TeamMaturity
    @e2e-test
# add your scenarios below
    # TODO: this is to allow the pipeline to work
    #       remove once real tests are added
    Scenario: Placeholder E2E Test
        Given foo
        When bar
        Then baz