/**
 * @file This file was generated by ax-app generator.
 * @copyright AvidXchange Inc.
 */
export const environment = {
  production: false,
  // TODO: revert to false when we hook up to platform
  mock: true,
};
