export enum AdvancedFiltersKeys {
  BuyerId = 'buyerId',
  BuyerName = 'buyerName',
  Supplier = 'supplier',
  ShipToName = 'shipToName',
  InvoiceNumber = 'invoiceNumber',
  SourceEmail = 'sourceEmail',
  DateReceived = 'dateReceived',
  DateSubmitted = 'dateSubmitted',
  IsSubmitted = 'isSubmitted',
  EscalationCategoryIssue = 'escalationCategoryIssue',
  EscalationLevel = 'escalationLevel',
  IngestionType = 'ingestionType',
  FileName = 'fileName',
  PropertyCode = 'propertyCode',
  LastModified = 'lastModified',
  LastModifiedByUser = 'lastModifiedByUser',
  SourceSystemBuyerId = 'sourceSystemBuyerId',
}
