export enum lookupLabels {
  CustomerAccountNumber = 'CustomerAccountNumber',
  Supplier = 'Supplier',
  SupplierAddress = 'SupplierAddress',
  ShipToName = 'ShipToName',
  ShipToAddress = 'ShipToAddress',
  OrderedBy = 'OrderedBy',
  Workflow = 'Workflow',
}

export enum nonLookupLabels {
  SupplierRegistrationCode = 'RegistrationCode',
  ShipToCode = 'PropertyCode',
  InvoiceNumber = 'InvoiceNumber',
  InvoiceDate = 'InvoiceDate',
  InvoiceAmount = 'InvoiceAmount',
  InvoiceDueDate = 'InvoiceDueDate',
  PurchaseOrderIdentifier = 'PurchaseOrderIdentifier',
  WorkOrderNo = 'WorkOrderNo',
  ServiceStartDate = 'ServiceStartDate',
  ServiceEndDate = 'ServiceEndDate',
  PreviousBalance = 'PreviousBalance',
  BuyerId = 'BuyerId',
  ShipToId = 'ShipToID',
  BuyerName = 'BuyerName',
  InvoiceType = 'InvoiceType',
  SupplierId = 'SupplierId',
  VendorName = 'VendorName',
  VendorAccountId = 'VendorAccountId',
  BillingAddressRecipient = 'BillingAddressRecipient',
  BillingAddress = 'BillingAddress',
  CustomerName = 'CustomerName',
  IngestionType = 'IngestionType',
  Terms = 'Terms',
  SourceEmail = 'SourceEmail',
  FileName = 'FileName',
  SupplierAlias = 'SupplierAlias',
  ShipToAlias = 'ShipToAlias',
  Memo = 'Memo',
  OrderedByName = 'OrderedByName',
  WorkflowName = 'WorkflowName',
  DisplayPredictedValues = 'DisplayPredictedValues',
  DisplayIdentifierSearchValues = 'DisplayIdentifierSearchValues',
  InvoiceDueDateOverride = 'InvoiceDueDateOverride',
  VendorExternalSystemID = 'VendorExternalSystemID',
  DateReceived = 'DateReceived',
  AccountingSystemId = 'AccountingSystemId',
}

export const DocumentLabelKeys = { lookupLabels, nonLookupLabels };
export type DocumentLabelKeys = typeof DocumentLabelKeys;
