/**
 * @file This file was generated by ax-app generator.
 * @copyright AvidXchange Inc.
 */
import { Controller, Get } from '@nestjs/common';
import { ApiResponse, ApiTags } from '@nestjs/swagger';

import { AppService } from './app.service';

@ApiTags('App Module')
@Controller()
export class AppController {
  constructor(private appService: AppService) {}

  /**
   * Api health check endpoint
   * @return {*}
   * @memberof AppController
   */
  @ApiResponse({ status: 200, description: 'Server is up.' })
  @Get('health')
  health() {
    return this.appService.health();
  }
}
