/**
 * @file This file was generated by ax-app generator.
 * @copyright AvidXchange Inc.
 */

import { MiddlewareConsumer, Module, NestModule, RequestMethod } from '@nestjs/common';
import { ConfigModule } from '@nestjs/config';

import { environment } from '../environments/environment';
import { HttpConfigService } from '../services/http-config.service';
import { AppController } from './app.controller';
import { AppService } from './app.service';
import { MOCK_ENV } from './shared';
import { UsrMgmtBffHttpModule } from './usr-mgmt-bff-http/usr-mgmt-bff-http.module';
import { UsersController, UsersService } from './controllers';
import { AppMiddleware } from './middleware';

@Module({
  imports: [ConfigModule.forRoot(), UsrMgmtBffHttpModule.register(environment.mock)],
  controllers: [AppController, UsersController],
  providers: [
    AppService,
    HttpConfigService,
    {
      provide: MOCK_ENV,
      useValue: environment.mock,
    },
    UsersService,
  ],
})
export class AppModule implements NestModule {
  configure(consumer: MiddlewareConsumer) {
    consumer
      .apply(AppMiddleware)
      .exclude({ path: 'api/health', method: RequestMethod.GET })
      .forRoutes({ path: '*', method: RequestMethod.ALL });
  }
}
