/**
 * @file This file was generated by ax-lib generator.
 * @copyright AvidXchange Inc.
 */
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  ButtonComponent,
  InputComponent,
  SideSheetComponent,
  DropdownComponent,
  SpinnerComponent,
  TagComponent,
} from '@ui-coe/shared/ui-v2';
import { ReactiveFormsModule } from '@angular/forms';
import {
  BusHierAddAddressComponent,
  BusHierPageHeaderComponent,
  BusHierPageTitleComponent,
  BusHierPageLayoutComponent,
  BusHierPageMainComponent,
  BusHierLoaderComponent,
  BusHierDetailsComponent,
  BusHierListComponent,
  BusHierLandingComponent,
  BusHierDetailsEditComponent,
  BusHierItemComponent,
  BusHierAddressComponent,
  BusHierActionableCardComponent,
  BusHierToggleCardComponent,
} from './components';
import { MatIconModule } from '@angular/material/icon';
@NgModule({
  declarations: [
    BusHierPageHeaderComponent,
    BusHierPageTitleComponent,
    BusHierPageLayoutComponent,
    BusHierPageMainComponent,
    BusHierLoaderComponent,
    BusHierDetailsEditComponent,
    BusHierDetailsComponent,
    BusHierListComponent,
    BusHierActionableCardComponent,
    BusHierLandingComponent,
    BusHierItemComponent,
    BusHierAddressComponent,
    BusHierAddAddressComponent,
    BusHierToggleCardComponent,
  ],
  exports: [
    BusHierPageHeaderComponent,
    BusHierPageLayoutComponent,
    BusHierPageTitleComponent,
    BusHierPageMainComponent,
    BusHierLoaderComponent,
    BusHierDetailsEditComponent,
    BusHierDetailsComponent,
    BusHierListComponent,
    BusHierListComponent,
    BusHierActionableCardComponent,
    BusHierItemComponent,
    BusHierAddressComponent,
    BusHierAddAddressComponent,
  ],
  imports: [
    CommonModule,
    ButtonComponent,
    InputComponent,
    SpinnerComponent,
    TagComponent,
    ReactiveFormsModule,
    SideSheetComponent,
    DropdownComponent,
    MatIconModule,
  ],
})
export class BusHierUiModule {}
